# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e787c4f30ceff9feb3dac26ea62c55f2dd9d2253b3a33a30c056396c7761955093f615e38bf1b2e02e6fe1a4eef042d06cf4ac5222968f046773957ba24cfcc

test:
  secret_key_base: 546594d28ef165122b30c761bb437d90cf9cbcaa85643f074df7f08bfaa033c7f8ef5fa6f2d44d19878ce03c4fe49d0170251733a9f6ec204718c7a92714190e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
